version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # 루트 비밀번호 설정
      MYSQL_DATABASE: mydatabase # 데이터베이스 이름
      MYSQL_USER: user # 사용자 이름
      MYSQL_PASSWORD: password # 사용자 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./main.go:/app/main.go
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
      - DB_RETRY_INTERVAL=5
      - DB_MAX_RETRIES=10
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
